# Generated by Django 6.0.4 on 2026-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
